import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
resources=[]
def add(id,title,provider,kind,topic,level,url,summary,use,access='Free to read',year='',doi=''):
 resources.append(dict(id=id,title=title,provider=provider,kind=kind,topic=topic,level=level,url=url,summary=summary,use=use,access=access,year=year,doi=doi,review='Source listing checked; full-content review pending',checked='2026-10-08'))
add('mit-devices','Microelectronic Devices and Circuits','MIT OpenCourseWare','Course','Devices','Intermediate','https://ocw.mit.edu/courses/6-012-microelectronic-devices-and-circuits-fall-2009/','Device modeling and circuit analysis, connecting physical behavior with junction and MOS device models.','Study the device models, then solve a selected circuit problem.',year='2009')
add('mit-processing','Micro/Nano Processing Technology','MIT OpenCourseWare','Course','Fabrication','Intermediate','https://ocw.mit.edu/courses/6-152j-micro-nano-processing-technology-fall-2005/','A university course covering micro/nano fabrication theory and processing techniques.','Map each unit process to its purpose, equipment and facility dependencies.',year='2005')
add('mit-lab','Micro/Nano Engineering Laboratory','MIT OpenCourseWare','Course','Testing','Intermediate','https://ocw.mit.edu/courses/2-674-micro-nano-engineering-laboratory-spring-2016/','Hands-on university learning through building, observing and manipulating small-scale structures.','Use the course as a reference when designing supervised learning activities.',year='2016')
add('mit-nano','Introduction to Nanoelectronics','MIT OpenCourseWare','Course','Devices','Advanced','https://ocw.mit.edu/courses/6-701-introduction-to-nanoelectronics-spring-2010/','A deeper university learning resource for nanoelectronic concepts.','Extend device foundations after completing introductory electronics.',year='2010')
add('semi-u','SEMI University','SEMI','Course','Workforce','Beginner','https://www.semi.org/en/semi-university','Industry-oriented semiconductor training and certification offerings.','Compare syllabus, prerequisites, current price and enrollment conditions before selection.','Mixed / paid offerings')
add('nptel-devices','Introduction to Semiconductor Devices','NPTEL / IIT Hyderabad','Course','Devices','Beginner','https://nptel.ac.in/courses/108106181','Semiconductor device foundations with an official syllabus and learning sequence.','Read the syllabus and check current course and certification availability.','Learning access; certification conditions vary')
add('asml-process','How Microchips Are Made','ASML','Guide','Fabrication','Beginner','https://www.asml.com/en/technology/all-about-microchips/how-microchips-are-made','An industry introduction to the main steps of microchip manufacturing.','Draw a process map and explain the role of lithography.')
add('asml-lithography','Lithography Principles','ASML','Guide','Fabrication','Intermediate','https://www.asml.com/en/technology/lithography-principles','An explanation of patterning principles from a lithography equipment manufacturer.','Identify how patterning accuracy affects manufacturing.')
add('asml-video','How Are Microchips Made? — ASML Nanoland','ASML','Video','Fabrication','Beginner','https://www.youtube.com/watch?v=Z-E5IUozd7M','An introductory video illustrating the microchip manufacturing sequence.','Watch alongside the manufacturing guide; create a glossary.','Free to watch')
add('asml-chip','What Is a Microchip and How Does It Work?','ASML','Video','Foundations','Beginner','https://www.youtube.com/watch?v=oI9DUata5-4','An industry video introducing chips and the machines used to make them.','Explain how a chip connects to everyday electronic systems.','Free to watch')
add('mit-circuits-video','Circuits and Electronics — Lecture 1','MIT OpenCourseWare','Video','Foundations','Beginner','https://www.youtube.com/watch?v=AfQxyVuLeCs','An introductory university circuits lecture.','Review voltage, current and circuit reasoning before device testing.','Free to watch',year='2007')
add('wiley-physics','Physics of Semiconductor Devices, Third Edition','Wiley · S. M. Sze and K. K. Ng','Book','Devices','Advanced','https://onlinelibrary.wiley.com/doi/book/10.1002/0470068329','An advanced reference on semiconductor device physics.','Use selected junction and MOS device chapters after the introductory pathway.','Purchase / institutional access',year='2007',doi='10.1002/0470068329')
add('cambridge-vlsi','Fundamentals of Modern VLSI Devices','Cambridge University Press','Book','Design','Advanced','https://www.cambridge.org/highereducation/books/fundamentals-of-modern-vlsi-devices/48B506E794B86E51D1EA3042DFCCF748','A reference for modern device behavior, modeling and scaling.','Check the edition and select chapters that match the intended curriculum.','Purchase / institutional access',doi='10.1017/9781108847087')
add('nist-pubs','CHIPS Research and Development Publications','NIST','Collection','Research','Intermediate','https://www.nist.gov/chips/publications','An official entry point for semiconductor research-program and standards publications.','Select a report; record authors, year, methods and limitations.')
add('nist-trust','Supply Chain Trust & Assurance and Digital Twin Data Interoperability','NIST','Report','Research','Advanced','https://doi.org/10.6028/NIST.CHIPS.1400-3','A workshop summary reporting community priorities for semiconductor assurance and interoperability.','Separate workshop recommendations from experimentally validated results.',year='2025',doi='10.6028/NIST.CHIPS.1400-3')
add('nist-chiplets','Chiplets Interfaces & Digital Twin Technical Standards Workshops','NIST','Report','Packaging','Advanced','https://doi.org/10.6028/NIST.CHIPS.1400-2','A workshop report on chiplet interfaces and digital twin technical standards.','Identify packaging-related interoperability questions for faculty discussion.',year='2024',doi='10.6028/NIST.CHIPS.1400-2')
add('nist-twins','Digital Twins Workshops Summary Report','NIST','Report','Research','Advanced','https://doi.org/10.6028/NIST.IR.8620','A report on digital twin fundamentals, barriers and research directions.','Compare the stated priorities with a proposed training simulation.',year='2026',doi='10.6028/NIST.IR.8620')
add('nanohub-paper','nanoHUB.org — Online Simulation and More Materials for Semiconductors','Purdue University repository','Paper','Research','Intermediate','https://docs.lib.purdue.edu/nanodocs/144/','A repository record about simulation and semiconductor education resources.','Read the full publication before extracting claims about learning outcomes.')
add('semi-workforce','Workforce Development','SEMI','Guide','Workforce','Beginner','https://www.semi.org/en/workforce-development','Industry workforce-development programs and talent pathways.','Identify which program goals align with your planned learner population.')
add('semi-asa','American Semiconductor Academy Initiative','SEMI','Guide','Workforce','Intermediate','https://www.semi.org/en/workforce-development/ASA','An initiative connecting universities and industry around microelectronics talent development.','Use as a collaboration reference; do not assume institutional membership.')
add('niosh-manufacturing','Manufacturing Worker Health and Safety','CDC / NIOSH','Guide','Facilities','Intermediate','https://www.cdc.gov/niosh/manufacturing/about/index.html','A general manufacturing health and safety research overview.','Use as background; facility-specific procedures require institutional EHS review.')
add('fau-hub','FAU Federal Funding Announcement','Florida Atlantic University','Guide','Workforce','Beginner','https://www.fau.edu/newsdesk/articles/federal-funding-announcement.php','FAU announced $1 million for a Chip Design Hub led by Professor Larrondo-Petrie within a $4 million multi-program award.','Read the institutional announcement; it does not establish a partnership with SiliconPath.',year='2026')
(root/'resources.json').write_text(json.dumps(resources,indent=2)+'\n')
